const MOCK_BASE_PORT = 4000
const MOCK_ETH_GAS_STATION_PORT = MOCK_BASE_PORT + 0
const MOCK_ETHERSCAN_PORT = MOCK_BASE_PORT + 1

export {
    MOCK_BASE_PORT,
    MOCK_ETH_GAS_STATION_PORT,
    MOCK_ETHERSCAN_PORT
}